### ISSUE TITLE
how to me can use this   in my source html

### ISSUE THREAD

**Issue by l3th2nh** [bisrael/CordovaFacebook#1]
thanks , i see code very clear , but how to me can use this  in my source html code like

facebook.init

facebook.login

facebook.logout 

Thanks

**Comment by bisrael** [comment]
@l3th2nh -- right now, i've only hooked up the event components of the facebook APIs, but if you want to fork the repot and add login/logout methods, i'd be happy too look at any pull requests.

cheers!

**Comment by bisrael** [comment]
@l3th2nh -- I added login/logout methods that will open facebook login dialogs and give you back login codes

Please see the README on how to use.

**Comment by l3th2nh** [comment]
Thanks :)  i am happy to know you :)
