### ISSUE TITLE
invalid hash key 

### ISSUE THREAD

**Issue by GamalSebaee** [bisrael/CordovaFacebook#22]
i have created hash key and used it in app setting in facebook
but not working and show message invalid hash key not equal any hash key

**Comment by vittorbraga** [comment]
Hi @GamalSebaee did you have any solution?

**Comment by GamalSebaee** [comment]
yes ,try this way 
this is way worked with me 
*************** soluation**************
This is how i solved this problem

Download your APK to your PC in java jdk\bin folder 

in my case founded in  C:\Program Files\Java\jdk1.7.0_121\bin

go to java jdk\bin folder and run cmd then
copy the following command in your cmd

keytool -list -printcert -jarfile yourapkname.apk

Copy the SHA1 value to your clip board
like this CD:A1:EA:A3:5C:5C:68:FB:FA:0A:6B:E5:5A:72:64:DD:26:8D:44:84
and open http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
This is what Facebook requires
get the generated hash " ********************= " and copy the key hash to the facebook app.
******
please try this soluation .

**Comment by vittorbraga** [comment]
Thank you @GamalSebaee. It worked for me.
