### ISSUE TITLE
Error: exec proxy not found 

### ISSUE THREAD

**Issue by potatoboy1999** [bisrael/CordovaFacebook#30]
I'm doing a project in **Phonegap** that requires an option to login with Facebook.
The installation of the plugin is correct but when i try it out on the browser i get the following message:

`Error: exec proxy not found for :: CordovaFacebook :: login`

Now, I understand that it only is supposed to work on Android or IOs so i also tried running the project in the phonegap app for Android that, as far as I understand it builds the project in a native Android enviroment. But even then it still doesn't work. I don't get any interaction to continue, like if my button wasn't working. I checked with some "alerts" with some messages and they appeared but the function dies once it gets to the `CordovaFacebook.login()`

Here's  the code i'm using if it's any help:

```
function getDataFB(e){
  //console.log('start FB');
  //alert('start FB');
  e.preventDefault();
  window.CordovaFacebook.login({
    permissions: ['email', 'user_likes'],
    onSuccess: function(result) {
      if(result.declined.length > 0) {
         alert("The User declined something!");
      }else{
         alert('Correct FB connection');
      }
    },
    onFailure: function(result) {
      if(result.cancelled) {
         alert("The user doesn't like my app");
      } else if(result.error) {
         alert("There was an error:" + result.errorLocalized);
      }
    }
  });
}
```

**Comment by vineckb** [comment]
I'm having some issue. Can I help me, please?
