### ISSUE TITLE
PGB(build.phonegap.com) will build fail by Android

### ISSUE THREAD

**Issue by bau720123** [bisrael/CordovaFacebook#8]
hi @bisrael 
awesome plugin
but when I am using PGB (build.phonegap.com) 5.1.1 and your plugin from npm
https://www.npmjs.com/package/cordova-plugin-facebook
it will cause only Android build fail (ios is build success)

these are build fail log information

```
Build Date: 2015-09-14 04:02:09 +0000
----------------------------------------------

/project/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Project contains at least one plugin that requires a system library. This is not supported with ANT. Please build using gradle.
    at /project/cordova/lib/build.js:183:27
    at _fulfilled (/project/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:760:13)
    at /project/cordova/node_modules/q/q.js:574:44
    at flush (/project/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
```

I know PGB for now not already support "gradle"
so...is there any way can change it or ... ?

**Comment by bisrael** [comment]
hey @bau720123 -- thanks for letting me know about this issue.

unfortunately, i have no plans to actively try to make this work with Ant as Cordova will no longer use it going forward.

I will happily look at any pull requests that could provide this, however.

best of luck!

**Comment by bau720123** [comment]
thanks @bisrael reply
got it
